/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as StyleFinderRouteImport } from './routes/style-finder'
import { Route as SwatchesRouteImport } from './routes/swatches'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutOurStoryRouteImport } from './routes/about/our-story'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout/payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout/review'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesCareRouteImport } from './routes/guides/care'
import { Route as GuidesMeasuringRouteImport } from './routes/guides/measuring'
import { Route as GuidesReturnsRouteImport } from './routes/guides/returns'
import { Route as GuidesShippingRouteImport } from './routes/guides/shipping'
import { Route as InspirationIndexRouteImport } from './routes/inspiration/index'
import { Route as InspirationSlugRouteImport } from './routes/inspiration/$slug'
import { Route as InspirationRoomsRouteImport } from './routes/inspiration/rooms'
import { Route as LegalAccessibilityRouteImport } from './routes/legal/accessibility'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesDesignConsultationRouteImport } from './routes/services/design-consultation'
import { Route as ServicesMeasuringInstallationRouteImport } from './routes/services/measuring-installation'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCategoryRouteImport } from './routes/shop/$category'
import { Route as InspirationRoomsIndexRouteImport } from './routes/inspiration/rooms/index'
import { Route as InspirationRoomsSlugRouteImport } from './routes/inspiration/rooms/$slug'
import { Route as ShopNeedsIndexRouteImport } from './routes/shop/needs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleFinderRoute = StyleFinderRouteImport.update({
  id: '/style-finder',
  path: '/style-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const SwatchesRoute = SwatchesRouteImport.update({
  id: '/swatches',
  path: '/swatches',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCareRoute = GuidesCareRouteImport.update({
  id: '/guides/care',
  path: '/guides/care',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesMeasuringRoute = GuidesMeasuringRouteImport.update({
  id: '/guides/measuring',
  path: '/guides/measuring',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReturnsRoute = GuidesReturnsRouteImport.update({
  id: '/guides/returns',
  path: '/guides/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesShippingRoute = GuidesShippingRouteImport.update({
  id: '/guides/shipping',
  path: '/guides/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationIndexRoute = InspirationIndexRouteImport.update({
  id: '/inspiration/',
  path: '/inspiration/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationSlugRoute = InspirationSlugRouteImport.update({
  id: '/inspiration/$slug',
  path: '/inspiration/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoomsRoute = InspirationRoomsRouteImport.update({
  id: '/inspiration/rooms',
  path: '/inspiration/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/legal/accessibility',
  path: '/legal/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDesignConsultationRoute =
  ServicesDesignConsultationRouteImport.update({
    id: '/services/design-consultation',
    path: '/services/design-consultation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMeasuringInstallationRoute =
  ServicesMeasuringInstallationRouteImport.update({
    id: '/services/measuring-installation',
    path: '/services/measuring-installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoomsIndexRoute = InspirationRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspirationRoomsRoute,
} as any)
const InspirationRoomsSlugRoute = InspirationRoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InspirationRoomsRoute,
} as any)
const ShopNeedsIndexRoute = ShopNeedsIndexRouteImport.update({
  id: '/shop/needs/',
  path: '/shop/needs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/quote': typeof QuoteRoute
  '/search': typeof SearchRoute
  '/smart-home': typeof SmartHomeRoute
  '/style-finder': typeof StyleFinderRoute
  '/swatches': typeof SwatchesRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/guides/care': typeof GuidesCareRoute
  '/guides/measuring': typeof GuidesMeasuringRoute
  '/guides/returns': typeof GuidesReturnsRoute
  '/guides/shipping': typeof GuidesShippingRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/inspiration/rooms': typeof InspirationRoomsRouteWithChildren
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/design-consultation': typeof ServicesDesignConsultationRoute
  '/services/measuring-installation': typeof ServicesMeasuringInstallationRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/about/': typeof AboutIndexRoute
  '/account/': typeof AccountIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/inspiration/': typeof InspirationIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/inspiration/rooms/$slug': typeof InspirationRoomsSlugRoute
  '/inspiration/rooms/': typeof InspirationRoomsIndexRoute
  '/shop/needs/': typeof ShopNeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/quote': typeof QuoteRoute
  '/search': typeof SearchRoute
  '/smart-home': typeof SmartHomeRoute
  '/style-finder': typeof StyleFinderRoute
  '/swatches': typeof SwatchesRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/guides/care': typeof GuidesCareRoute
  '/guides/measuring': typeof GuidesMeasuringRoute
  '/guides/returns': typeof GuidesReturnsRoute
  '/guides/shipping': typeof GuidesShippingRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/design-consultation': typeof ServicesDesignConsultationRoute
  '/services/measuring-installation': typeof ServicesMeasuringInstallationRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/about': typeof AboutIndexRoute
  '/account': typeof AccountIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/inspiration': typeof InspirationIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/inspiration/rooms/$slug': typeof InspirationRoomsSlugRoute
  '/inspiration/rooms': typeof InspirationRoomsIndexRoute
  '/shop/needs': typeof ShopNeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/quote': typeof QuoteRoute
  '/search': typeof SearchRoute
  '/smart-home': typeof SmartHomeRoute
  '/style-finder': typeof StyleFinderRoute
  '/swatches': typeof SwatchesRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/guides/care': typeof GuidesCareRoute
  '/guides/measuring': typeof GuidesMeasuringRoute
  '/guides/returns': typeof GuidesReturnsRoute
  '/guides/shipping': typeof GuidesShippingRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/inspiration/rooms': typeof InspirationRoomsRouteWithChildren
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/services/design-consultation': typeof ServicesDesignConsultationRoute
  '/services/measuring-installation': typeof ServicesMeasuringInstallationRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/about/': typeof AboutIndexRoute
  '/account/': typeof AccountIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/inspiration/': typeof InspirationIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/inspiration/rooms/$slug': typeof InspirationRoomsSlugRoute
  '/inspiration/rooms/': typeof InspirationRoomsIndexRoute
  '/shop/needs/': typeof ShopNeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/quote'
    | '/search'
    | '/smart-home'
    | '/style-finder'
    | '/swatches'
    | '/trade'
    | '/wishlist'
    | '/about/our-story'
    | '/checkout/payment'
    | '/checkout/review'
    | '/collections/$slug'
    | '/guides/care'
    | '/guides/measuring'
    | '/guides/returns'
    | '/guides/shipping'
    | '/inspiration/$slug'
    | '/inspiration/rooms'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/product/$slug'
    | '/services/design-consultation'
    | '/services/measuring-installation'
    | '/shop/$category'
    | '/about/'
    | '/account/'
    | '/collections/'
    | '/guides/'
    | '/inspiration/'
    | '/services/'
    | '/shop/'
    | '/inspiration/rooms/$slug'
    | '/inspiration/rooms/'
    | '/shop/needs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/quote'
    | '/search'
    | '/smart-home'
    | '/style-finder'
    | '/swatches'
    | '/trade'
    | '/wishlist'
    | '/about/our-story'
    | '/checkout/payment'
    | '/checkout/review'
    | '/collections/$slug'
    | '/guides/care'
    | '/guides/measuring'
    | '/guides/returns'
    | '/guides/shipping'
    | '/inspiration/$slug'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/product/$slug'
    | '/services/design-consultation'
    | '/services/measuring-installation'
    | '/shop/$category'
    | '/about'
    | '/account'
    | '/collections'
    | '/guides'
    | '/inspiration'
    | '/services'
    | '/shop'
    | '/inspiration/rooms/$slug'
    | '/inspiration/rooms'
    | '/shop/needs'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/quote'
    | '/search'
    | '/smart-home'
    | '/style-finder'
    | '/swatches'
    | '/trade'
    | '/wishlist'
    | '/about/our-story'
    | '/checkout/payment'
    | '/checkout/review'
    | '/collections/$slug'
    | '/guides/care'
    | '/guides/measuring'
    | '/guides/returns'
    | '/guides/shipping'
    | '/inspiration/$slug'
    | '/inspiration/rooms'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/product/$slug'
    | '/services/design-consultation'
    | '/services/measuring-installation'
    | '/shop/$category'
    | '/about/'
    | '/account/'
    | '/collections/'
    | '/guides/'
    | '/inspiration/'
    | '/services/'
    | '/shop/'
    | '/inspiration/rooms/$slug'
    | '/inspiration/rooms/'
    | '/shop/needs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  QuoteRoute: typeof QuoteRoute
  SearchRoute: typeof SearchRoute
  SmartHomeRoute: typeof SmartHomeRoute
  StyleFinderRoute: typeof StyleFinderRoute
  SwatchesRoute: typeof SwatchesRoute
  TradeRoute: typeof TradeRoute
  WishlistRoute: typeof WishlistRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  GuidesCareRoute: typeof GuidesCareRoute
  GuidesMeasuringRoute: typeof GuidesMeasuringRoute
  GuidesReturnsRoute: typeof GuidesReturnsRoute
  GuidesShippingRoute: typeof GuidesShippingRoute
  InspirationSlugRoute: typeof InspirationSlugRoute
  InspirationRoomsRoute: typeof InspirationRoomsRouteWithChildren
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ServicesDesignConsultationRoute: typeof ServicesDesignConsultationRoute
  ServicesMeasuringInstallationRoute: typeof ServicesMeasuringInstallationRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  InspirationIndexRoute: typeof InspirationIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopNeedsIndexRoute: typeof ShopNeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-finder': {
      id: '/style-finder'
      path: '/style-finder'
      fullPath: '/style-finder'
      preLoaderRoute: typeof StyleFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swatches': {
      id: '/swatches'
      path: '/swatches'
      fullPath: '/swatches'
      preLoaderRoute: typeof SwatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-story': {
      id: '/about/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/care': {
      id: '/guides/care'
      path: '/guides/care'
      fullPath: '/guides/care'
      preLoaderRoute: typeof GuidesCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/measuring': {
      id: '/guides/measuring'
      path: '/guides/measuring'
      fullPath: '/guides/measuring'
      preLoaderRoute: typeof GuidesMeasuringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/returns': {
      id: '/guides/returns'
      path: '/guides/returns'
      fullPath: '/guides/returns'
      preLoaderRoute: typeof GuidesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/shipping': {
      id: '/guides/shipping'
      path: '/guides/shipping'
      fullPath: '/guides/shipping'
      preLoaderRoute: typeof GuidesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/': {
      id: '/inspiration/'
      path: '/inspiration'
      fullPath: '/inspiration/'
      preLoaderRoute: typeof InspirationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/$slug': {
      id: '/inspiration/$slug'
      path: '/inspiration/$slug'
      fullPath: '/inspiration/$slug'
      preLoaderRoute: typeof InspirationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/rooms': {
      id: '/inspiration/rooms'
      path: '/inspiration/rooms'
      fullPath: '/inspiration/rooms'
      preLoaderRoute: typeof InspirationRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/design-consultation': {
      id: '/services/design-consultation'
      path: '/services/design-consultation'
      fullPath: '/services/design-consultation'
      preLoaderRoute: typeof ServicesDesignConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/measuring-installation': {
      id: '/services/measuring-installation'
      path: '/services/measuring-installation'
      fullPath: '/services/measuring-installation'
      preLoaderRoute: typeof ServicesMeasuringInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/rooms/': {
      id: '/inspiration/rooms/'
      path: '/'
      fullPath: '/inspiration/rooms/'
      preLoaderRoute: typeof InspirationRoomsIndexRouteImport
      parentRoute: typeof InspirationRoomsRoute
    }
    '/inspiration/rooms/$slug': {
      id: '/inspiration/rooms/$slug'
      path: '/$slug'
      fullPath: '/inspiration/rooms/$slug'
      preLoaderRoute: typeof InspirationRoomsSlugRouteImport
      parentRoute: typeof InspirationRoomsRoute
    }
    '/shop/needs/': {
      id: '/shop/needs/'
      path: '/shop/needs'
      fullPath: '/shop/needs/'
      preLoaderRoute: typeof ShopNeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface InspirationRoomsRouteChildren {
  InspirationRoomsSlugRoute: typeof InspirationRoomsSlugRoute
  InspirationRoomsIndexRoute: typeof InspirationRoomsIndexRoute
}

const InspirationRoomsRouteChildren: InspirationRoomsRouteChildren = {
  InspirationRoomsSlugRoute: InspirationRoomsSlugRoute,
  InspirationRoomsIndexRoute: InspirationRoomsIndexRoute,
}

const InspirationRoomsRouteWithChildren =
  InspirationRoomsRoute._addFileChildren(InspirationRoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  QuoteRoute: QuoteRoute,
  SearchRoute: SearchRoute,
  SmartHomeRoute: SmartHomeRoute,
  StyleFinderRoute: StyleFinderRoute,
  SwatchesRoute: SwatchesRoute,
  TradeRoute: TradeRoute,
  WishlistRoute: WishlistRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  GuidesCareRoute: GuidesCareRoute,
  GuidesMeasuringRoute: GuidesMeasuringRoute,
  GuidesReturnsRoute: GuidesReturnsRoute,
  GuidesShippingRoute: GuidesShippingRoute,
  InspirationSlugRoute: InspirationSlugRoute,
  InspirationRoomsRoute: InspirationRoomsRouteWithChildren,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ServicesDesignConsultationRoute: ServicesDesignConsultationRoute,
  ServicesMeasuringInstallationRoute: ServicesMeasuringInstallationRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  AboutIndexRoute: AboutIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  InspirationIndexRoute: InspirationIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopNeedsIndexRoute: ShopNeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
